[project]
name = "airgap-web-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "trafilatura",
    "sentence-transformers",
    "faiss-cpu",
    "ollama",
    "pytest",
    "httpx",
    "pydantic"
]

[project.scripts]
airgap-web-copilot = "airgap_web_copilot:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
