"""Local Ollama async copilot service with streaming RAG responses and graceful error handling."""

import json
import os
import re
from typing import Any, AsyncGenerator, Dict, List, Optional
import httpx
import ollama


DEFAULT_OLLAMA_HOST = "http://localhost:11434"


def get_default_host() -> str:
    """Retrieve the configured Ollama host URL from environment or fallback."""
    return os.getenv("OLLAMA_HOST", DEFAULT_OLLAMA_HOST)


async def get_ollama_client(host: Optional[str] = None) -> ollama.AsyncClient:
    """Create an asynchronous Ollama client."""
    target_host = host or get_default_host()
    return ollama.AsyncClient(host=target_host)


async def check_ollama_status(host: Optional[str] = None) -> Dict[str, Any]:
    """Check whether the local Ollama daemon is running and retrieve available models."""
    target_host = host or get_default_host()
    try:
        async with httpx.AsyncClient(timeout=1.5) as client:
            resp = await client.get(f"{target_host.rstrip('/')}/api/tags")
            if resp.status_code == 200:
                data = resp.json()
                models = [m.get("name") for m in data.get("models", []) if m.get("name")]
                return {
                    "connected": True,
                    "models": models,
                    "model": models[0] if models else None,
                }
    except Exception as e:
        return {
            "connected": False,
            "models": [],
            "model": None,
            "error": str(e),
        }

    return {
        "connected": False,
        "models": [],
        "model": None,
    }


async def stream_rag_response(
    context: str,
    user_prompt: str,
    model: str = "qwen2.5:7b",
    host: Optional[str] = None,
    client: Optional[ollama.AsyncClient] = None,
) -> AsyncGenerator[str, None]:
    """Stream grounded response tokens from local Ollama using document context.

    Args:
        context: The extracted and retrieved document context.
        user_prompt: The user query or question.
        model: Ollama model identifier (default: "qwen2.5:7b").
        host: Ollama daemon URL (defaults to OLLAMA_HOST or http://localhost:11434).
        client: Optional pre-configured ollama.AsyncClient.


    Yields:
        Text chunks as they are generated by the LLM, or informative error messages.
    """
    target_host = host or get_default_host()
    if client is None:
        client = ollama.AsyncClient(host=target_host)

    # If default model is requested, check if it or another model is installed
    target_model = model
    try:
        status = await check_ollama_status(target_host)
        available = status.get("models", [])
        if available and target_model not in available:
            # If default qwen is not installed, use the user's installed model directly
            target_model = available[0]
    except Exception:
        pass

    system_prompt = (
        "You are an air-gapped web copilot running completely offline. "
        "Answer the user's question accurately and strictly based on the provided webpage context. "
        "If the context does not contain enough information to answer the question, state that clearly."
    )

    clean_context = (context or "").strip()
    user_content = f"Webpage Context:\n{clean_context}\n\nQuestion: {user_prompt}" if clean_context else user_prompt

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    # Attempt generation with target model
    try:
        response = await client.chat(model=target_model, messages=messages, stream=True)
        async for chunk in response:
            content = chunk.get("message", {}).get("content", "")
            if content:
                yield content
        return

    except (httpx.ConnectError, httpx.ConnectTimeout, ConnectionRefusedError, ollama.RequestError) as conn_err:
        yield (
            f"[Error: Ollama daemon is offline or unreachable at {target_host}. "
            f"Please ensure Ollama is installed and running locally. Details: {conn_err}]"
        )
        return

    except ollama.ResponseError as resp_err:
        # Check if the error is due to a missing model (404 / 'not found')
        err_msg = str(resp_err).lower()
        if "not found" in err_msg or getattr(resp_err, "status_code", 0) == 404:
            # Check if any alternative model is available in Ollama
            status = await check_ollama_status(target_host)
            available = status.get("models", [])
            if available:
                fallback_model = available[0]
                yield (
                    f"_[Notice: Requested model '{model}' was not found. "
                    f"Falling back to installed model '{fallback_model}'...]_\n\n"
                )
                try:
                    fallback_stream = await client.chat(
                        model=fallback_model,
                        messages=messages,
                        stream=True,
                    )
                    async for chunk in fallback_stream:
                        content = chunk.get("message", {}).get("content", "")
                        if content:
                            yield content
                    return
                except Exception as fb_err:
                    yield f"[Error running fallback model '{fallback_model}': {fb_err}]"
                    return
            else:
                yield (
                    f"[Error: Model '{model}' not found in local Ollama and no other models are installed. "
                    f"Run `ollama pull {model}` in your terminal to download it.]"
                )
                return
        else:
            yield f"[Ollama Response Error: {resp_err}]"
            return

    except Exception as exc:
        yield f"[Unexpected error communicating with Ollama: {exc}]"
        return


async def evaluate_groundedness(
    context: str,
    user_prompt: str,
    answer: str,
    model: Optional[str] = None,
    host: Optional[str] = None,
    client: Optional[ollama.AsyncClient] = None,
) -> Dict[str, Any]:
    """Audit and verify an answer against retrieved document context using a Judge model.

    Evaluates:
    - Faithfulness: Are factual assertions in the answer strictly supported by the context?
    - Hallucination detection: Are there claims unmentioned or contradicted by the context?
    - Relevance: Did the answer address the question?

    Returns:
        Dict with status ("verified" | "flagged" | "inconclusive"),
        groundedness_score (float 0.0 - 1.0), verdict explanation,
        judge_model used, and lists of supported vs unsupported claims.
    """
    target_host = host or get_default_host()
    if client is None:
        client = ollama.AsyncClient(host=target_host)

    # Check Ollama connection and determine judge model
    judge_model = model
    try:
        status = await check_ollama_status(target_host)
        if not status.get("connected"):
            return {
                "status": "inconclusive",
                "score": 0.0,
                "verdict": "Local Ollama daemon is offline or unreachable. Groundedness check inconclusive.",
                "judge_model": "none",
                "supported_claims": [],
                "unsupported_claims": [],
            }
        available = status.get("models", [])
        if not judge_model or judge_model not in available:
            judge_model = available[0] if available else "llama3.2"
    except Exception as exc:
        return {
            "status": "inconclusive",
            "score": 0.0,
            "verdict": f"Could not connect to Ollama judge: {exc}",
            "judge_model": "none",
            "supported_claims": [],
            "unsupported_claims": [],
        }

    clean_context = (context or "").strip()[:4000]
    clean_answer = (answer or "").strip()[:4000]
    clean_query = (user_prompt or "").strip()[:1000]

    system_prompt = (
        "You are an impartial factual evaluation judge. Your task is to audit an AI-generated answer "
        "against the provided source webpage context.\n"
        "Instructions:\n"
        "1. Check whether all factual statements in the answer are directly supported by the context.\n"
        "2. Identify any unsupported claims, hallucinations, or extrapolations.\n"
        "3. Assign a groundedness score between 0.0 and 1.0 (1.0 = fully grounded in context, 0.0 = completely hallucinated).\n"
        "4. Determine status: 'verified' (score >= 0.75), 'flagged' (score < 0.75), or 'inconclusive'.\n"
        "5. Respond STRICTLY in valid JSON matching this exact structure without markdown backticks:\n"
        "{\n"
        '  "status": "verified",\n'
        '  "score": 0.95,\n'
        '  "verdict": "One sentence summary of your evaluation.",\n'
        '  "supported_claims": ["claim 1", "claim 2"],\n'
        '  "unsupported_claims": []\n'
        "}"
    )

    user_content = (
        f"Source Webpage Context:\n{clean_context}\n\n"
        f"User Question:\n{clean_query}\n\n"
        f"Proposed Answer To Evaluate:\n{clean_answer}"
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    try:
        response = await client.chat(model=judge_model, messages=messages, stream=False)
        raw_output = response.get("message", {}).get("content", "").strip()

        # Parse JSON output robustly
        json_match = re.search(r"\{.*\}", raw_output, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(0))
            score = float(data.get("score", 0.8))
            score = max(0.0, min(1.0, score))
            status = data.get("status", "verified" if score >= 0.75 else "flagged")
            return {
                "status": status,
                "score": round(score, 2),
                "verdict": str(data.get("verdict", "Evaluation completed.")),
                "judge_model": judge_model,
                "supported_claims": list(data.get("supported_claims", [])),
                "unsupported_claims": list(data.get("unsupported_claims", [])),
            }
        else:
            # Fallback if model didn't format strict JSON
            is_positive = "verified" in raw_output.lower() or "accurate" in raw_output.lower()
            return {
                "status": "verified" if is_positive else "flagged",
                "score": 0.85 if is_positive else 0.5,
                "verdict": raw_output[:200],
                "judge_model": judge_model,
                "supported_claims": [],
                "unsupported_claims": [],
            }
    except Exception as exc:
        return {
            "status": "inconclusive",
            "score": 0.0,
            "verdict": f"Judge evaluation error: {exc}",
            "judge_model": judge_model,
            "supported_claims": [],
            "unsupported_claims": [],
        }

